const base = { age: "adult", emergency: "no" };
const cases = {
  pineal: {
    ...base,
    modality: "MRI",
    size: 11,
    structure: "simple",
    obstruction: "no",
    presentation: "none",
    stage: "initial",
  },
  pituitary: {
    ...base,
    size: 9,
    composition: "solid",
    optic: "clear",
    endocrine: "normal",
    visual: "no",
    change: "baseline",
  },
  arachnoid: {
    ...base,
    size: 20,
    signal: "typical",
    location: "low",
    hydro: "no",
    related: "no",
    change: "baseline",
  },
  colloid: {
    ...base,
    years: 70,
    size: 6,
    headache: "no",
    flair: "notHigh",
    riskZone: "no",
    hydro: "no",
    change: "baseline",
  },
  meningioma: {
    ...base,
    size: 20,
    edema: "no",
    critical: "no",
    related: "no",
    certainty: "typical",
    change: "baseline",
  },
  vestibular: {
    ...base,
    size: 5,
    extent: "small",
    hearing: "stable",
    change: "baseline",
  },
  white: {
    ...base,
    pattern: "vascular",
    history: "none",
    risks: "controlled",
    change: "baseline",
  },
  aneurysm: {
    ...base,
    years: 55,
    fitness: "candidate",
    size: 4,
    location: "ica",
    shape: "regular",
    related: "no",
    priorSAH: "no",
    risk: "no",
    change: "baseline",
  },
  carotid: {
    ...base,
    anatomy: "conventional",
    stenosis: 55,
    ischemia: "none",
    measurement: "confirmed",
    candidate: "yes",
    highRisk: "no",
  },
  dva: { ...base, isolation: "isolated", related: "no" },
  cavernous: {
    ...base,
    location: "lobar",
    bleed: "no",
    seizure: "no",
    burden: "single",
    mri: "adequate",
    change: "baseline",
  },
  skull: {
    ...base,
    appearance: "benign",
    cancer: "no",
    pain: "no",
    modality: "both",
    change: "baseline",
  },
};

module.exports = cases;
